server:
  port: 8080
  host: localhost
  features:
    security:
      enabled: false
      defaults:
        authenticate: true
      web-server:
        # protected paths on the web server - do not include paths served by Jersey, as those are protected directly
        paths:

app:
    greeting: "Hello"

tracing:
  service: helidon-tracing-service

db:
  source: jdbc
  connection:
    url: jdbc:postgresql://localhost:9999/appdb?useSSL=false
    username: admin
    password: adminpass
    initializationFailTimeout: -1
    connectionTimeout: 2000
  health-check:
    type: "query"
    statementName: "health-check"
  statements:
    health-check: "SELECT 0"
    create-types: "CREATE TABLE PokeTypes (poke_types_id SERIAL NOT NULL PRIMARY KEY, name VARCHAR(64) NOT NULL);"
    create-pokemons: "CREATE TABLE Pokemons (pokemons_id SERIAL NOT NULL PRIMARY KEY, name VARCHAR(64) NOT NULL, id_type INTEGER NOT NULL REFERENCES PokeTypes(poke_types_id))"
    select-all-types: "SELECT poke_types_id, name FROM PokeTypes"
    select-all-pokemons: "SELECT pokemons_id, name, id_type FROM Pokemons"
    select-pokemon-by-id: "SELECT pokemons_id, name, id_type FROM Pokemons WHERE id = :id"
    select-pokemon-by-name: "SELECT pokemons_id, name, id_type FROM Pokemons WHERE name = ?"
    insert-type: "INSERT INTO PokeTypes(name) VALUES(?)"
    insert-pokemon: "INSERT INTO Pokemons(name, id_type) VALUES(?, ?)"
    update-pokemon-by-id: "UPDATE Pokemons SET name = :name, id_type = :idType WHERE pokemons_id = :id"
    delete-pokemon-by-id: "DELETE FROM Pokemons WHERE pokemons_id = :id"
    delete-all-types: "DELETE FROM PokeTypes"
    delete-all-pokemons: "DELETE FROM Pokemons"
    drop-schema-and-recreate: "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"

security:
  config.require-encryption: false
  properties:
  providers:


